# Análise Espacial com R

## Plotagem de modo Espacial e 3D

Vamos carregar dados de terremotos na Oceania, do objetos quakes

```
data(quakes)

quakes %>%
  kable()%>%
  kable_styling(bootstrap_options = "striped",
                full_width = TRUE,
                font_size = 12)
```

Vamos transformar este data frame em um shapefile, para que possamos plotá-lo de forma espacial

```{r}
class(quakes)

sf_terremotos <- st_as_sf(x = quakes, 
                          coords = c("long", "lat"), 
                          crs = 4326)

sf_terremotos %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped",
                full_width = TRUE,
                font_size = 12)
tmap_mode("view")

tm_shape(sf_terremotos) +
  tm_dots(size = 0.5, alpha = 0.3)
```

Vamos estratificar o gráfico pela profundida do terremoto, por tamanho das esferas e depois por cor

```{r}

#Tamanho
tm_shape(shp = sf_terremotos) +
  tm_bubbles(size = "depth",
             scale = 1,
             shape = 19,
             alpha = 0.3,
             title.size = "Profundidade dos Terremotos") +
  tm_compass() +
  tm_layout(legend.outside = TRUE,
            legend.text.size = 3)

#Cor
tm_shape(shp = sf_terremotos) +
  tm_dots(col = "depth",
          shape = 19,
          alpha = 0.5,
          size = 0.6,
          palette = "viridis",
          title.size = "Profundidade dos Terremotos") +
  tm_compass() +
  tm_layout(legend.outside = TRUE,
            legend.text.size = 3)
```

Vamos plotar os dois mapas em conjunto:

````{r}
#Salvar cada mapa em objetos diferentes:

plot_01 <- tm_shape(shp = sf_terremotos) +
  tm_bubbles(size = "depth", 
             scale = 1, 
             shape = 19, 
             alpha = 0.3,
             title.size = "Profundidade dos Terremotos") +
  tm_compass() +
  tm_layout(legend.outside = TRUE)


plot_02 <- tm_shape(shp = sf_terremotos) +
  tm_dots(col = "depth", 
          shape = 19, 
          alpha = 0.5, 
          size = 0.6, 
          palette = "viridis", 
          title = "Profundidade dos Terremotos") +
  tm_compass() +
  tm_layout(legend.outside = TRUE)

#Preparar o ambiente gráfico do R para receber gráficos de forma simultânea:

pushViewport(
  viewport(
    layout = grid.layout(1,2)))

#Executar as plotagens:

print(plot_01, vp = viewport(layout.pos.col = 1, height = 5))
print(plot_02, vp = viewport(layout.pos.col = 2, height = 5))

sf_terremotos %>% 
  filter(mag >= 2) %>% 
  tm_shape() +
  tm_dots(col = "depth", 
          shape = 19, 
          alpha = 0.5, 
          size = 0.2, 
          palette = "-plasma", 
          title = "Profundidade dos Terremotos")
```

FIM ------------------------------------------------------------------------------------------------
